library(readr)
library(dplyr)
library(tidyr)
library(psych)
library(reshape2)
library(corrplot)
library(ggplot2)
library(ggthemes)
theme_set(theme_gdocs())
house = read_csv('train.csv') %>% select(-Id)