library(stringr)
library(readr)
library(dplyr)
library(tidyr)
library(highcharter)
library(ggplot2)
library(ggthemes)
library(ggmap)
library(gganimate)
library(plotly)
library(countrycode)
library(knitr)
theme_set(theme_minimal())

setwd('/Users/aminrakhsha/Documents/University/Term4 - 97spring/Data Analysis/HW/HW11')
sequake = read_rds("data/historical_web_data_26112015.rds")
disaster = read_delim("data/disaster.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
iequake = read_rds("data/iran_earthquake.rds")
earthquakes = read_csv('data/worldwide.csv') %>% filter(type == 'earthquake')

