library(stringr)
library(readr)
library(tidyr)
library(highcharter)
library(ggplot2)
library(ggthemes)
library(WDI)
library(countrycode)
library(ggpubr)
library(ggbiplot)
library(dplyr)
library(knitr)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

setwd('/Users/aminrakhsha/Documents/University/Term4 - 97spring/Data Analysis/HW/HW10')
series = read_csv('data/WDISeries.csv')
countryNames = read_csv('data/WDICountry.csv')
data = read_csv('data/WDIData.csv')
set.seed(100)

